previewsEnabled: true
services:
  - type: cron
    name: nouns250-merkle-cron
    plan: starter
    previewPlan: starter
    env: node
    region: oregon
    rootDir: ./
    schedule: "0 * * * *"
    buildCommand: ./scripts/setup_merkle_cron.sh
    startCommand: pnpm -F nym-merkle-tree run writeTree
    buildFilter:
      paths:
      - packages/merkle_tree/**
      - packages/db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nouns250
          property: connectionString
      - fromGroup: nouns250

databases:
  - name: nouns250
    databaseName: nym
    region: oregon
    plan: starter
    postgresMajorVersion: 15