export const INVALID_MERKLE_ROOT = 'Invalid merkle root!';
export const INVALID_PROOF = 'Invalid proof!';
export const INVALID_TIMESTAMP = 'Invalid timestamp!';
export const INVALID_SIGNATURE = 'Invalid signature!';
export const USER_NOT_IN_LATEST_GROUP = 'Public key not in latest group';
export const ALREADY_UPVOTED = 'Already upvoted';
export const PARENT_NOT_FOUND = 'Parent not found';
export const EMPTY_TITLE = 'Title cannot be empty';
export const EMPTY_BODY = 'Body cannot be empty';
