version: '3.8'
services:
  database:
    image: "postgres:14"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nymdev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nym
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: