# .github/workflows/test.yml
name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test
