# .github/workflows/test.yml
name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 19.7
        uses: actions/setup-node@v3
        with:
          node-version: 19.7
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
