# .github/workflows/test.yml
name: Nym CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.14.0]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run database migrations
        # Run migrations only on pull requests and pushes to the main branch
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: pnpm -F db run migrate:prod
        env:
          # If the event is a push to the main branch, we run migration on the production database
          # If the event is a pull request, we run migration on the staging database
          DATABASE_URL: ${{ secrets[github.event_name == 'push' && 'DATABASE_URL_PROD' || 'DATABASE_URL_STAGING'] }}
      